{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n"
     ]
    }
   ],
   "source": [
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: DATABASE_URL=postgresql://itversity_retail_user:itversity@host.docker.internal:5432/itversity_retail_db\n"
     ]
    }
   ],
   "source": [
    "%env DATABASE_URL=postgresql://itversity_retail_user:itversity@host.docker.internal:5432/itversity_retail_db"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3300, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 620, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"host.docker.internal\" (192.168.1.143), port 5432 failed: No route to host\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sql/connection.py\", line 78, in set\n",
      "    cls.current = Connection(\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sql/connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3276, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 148, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 2440, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3300, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 620, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/home/dbugan/Projects/Python/database-loader/dbl-venv/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"host.docker.internal\" (192.168.1.143), port 5432 failed: No route to host\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "SELECT * FROM orders\n",
    "LIMIT 10;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "help(pd.read_csv)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_column_names(schemas, ds_name, sorting_key='column_position'):\n",
    "    column_details = schemas[ds_name]\n",
    "    columns = sorted(column_details, key=lambda col: col[sorting_key])\n",
    "    return [col['column_name'] for col in columns]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "schemas = json.load(open('../data/retail_db/schemas.json'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds_name = 'orders'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds_name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "columns = get_column_names(schemas, 'orders')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('../data/retail_db/orders/part-00000', names=columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "type(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_reader = pd.read_csv(\n",
    "    f'../data/retail_db/{ds_name}/part-00000',\n",
    "    names=columns,\n",
    "    chunksize=10000\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for idx, df in enumerate(df_reader):\n",
    "    print(f'Size of chunk {idx} is {df.shape}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn_uri = 'postgresql://itversity_retail_user:itversity@host.docker.internal:5432/itversity_retail_db'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_reader = pd.read_csv(\n",
    "    '../data/retail_db/orders/part-00000',\n",
    "    names=columns,\n",
    "    chunksize=10000\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for idx, df in enumerate(df_reader):\n",
    "    print(f'Processing chunk {idx} with size {df.shape[0]} of {ds_name}')\n",
    "    df.to_sql(\n",
    "        'orders',\n",
    "        conn_uri,\n",
    "        if_exists='append',\n",
    "        index=False\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.read_sql(ds_name, conn_uri)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "dbl-venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
